### ISSUE TITLE
Erreur de reference lors du deploiement sur le moduel entrainement

### ISSUE THREAD

**Issue by mis7ern9o** [DstMlOpsCrypto/MainCrypto#142]
**Describe the bug**

**To Reproduce**
1. PR from Dev to Main

**Expected behavior**
l'entrainement se passe sans erreur

**Screenshots**
```bash
Conteneur trouvé : c5c404f09271. Connexion et lancement de l'entrainement...
Dossier de scripts atteint, lancement de l entrainement...
Traceback (most recent call last):
  File "/app/scripts/train.py", line 28, in <module>
    from src.data.import_raw_data import load_data, load_data_2, load_transform_data,load_transform_data2
  File "/app/src/data/import_raw_data.py", line 14, in <module>
Je suis bien passé par init_py dans le src
    from src.data.database import get_db
ModuleNotFoundError: No module named 'src.data.database'
Échec de l'exécution de la commande.
```

**Additional context**
Lancement du script 'setup.sh'

**Comment by mis7ern9o** [comment]
@FredericLAGNIEZ , la ligne import_raw_data.py dans src:data/import_raw_data.py " pointe sur un fichier database inconnu !

**Comment by FredericLAGNIEZ** [comment]
Git error, done
